@startuml
autonumber

- -> LogsController: getAllLogs()
LogsController -> LogsFacade: getAllLogs()
LogsFacade -> DAOFactory : getLogsDAO()
DAOFactory -> LogsDAO ++ : <<creates>>
LogsDAO -> DAOFactory
DAOFactory -> LogsFacade : LogsDAO
LogsFacade -> LogsDAO : getAllLogs()
LogsDAO -> LogsFacade : logs[]
deactivate LogsDAO
alt getAllLogs was succeed
  LogsFacade -> LogsController : log was returned
else any other error
  LogsFacade -> LogsController: internal error
end
@enduml
