@startuml
package controller {

  class LogsController {
    -searchLogsButton: Button
    +getLogs() : void
  }
}

package logs {

  class LogsFacade {
    +getAll() : logs[]
  }

}

package dao {

  abstract class DAOFactory {
    +getLogDAO(): LogsDAO
  }

  interface LogsDAO {
    +getAll() : logs[]
  }

  package postgres {

    class PostgresLogsDAO implements LogsDAO {
      -connection: Connection
      +PostgresLogsDAO(Connection: connection)
    }

    class PostgresDAOFactory extends DAOFactory {
      -connection: Connection
    }
  }

}

PostgresDAOFactory .left> PostgresLogsDAO : "creates"
DAOFactory .left> LogsDAO : "provides"
LogsFacade -down-> DAOFactory
LogsController -down-> LogsFacade
@enduml