@startuml Display recommended library items

left to right direction

actor Client as cl
actor Employee as em
actor Administrator as ad

rectangle "List recommended library items" {
  usecase "List recommended library items" as Li
  usecase "List recommended library items for a given client" as Lc
 
}

cl -- Li
em -- Lc
ad -|> em

@enduml
