@startuml

autonumber

-> LibraryItemFormController : create()
LibraryItemFormController -> LibraryItemFormController : getItemFromFields()
LibraryItemFormController -> LibraryItemFacade : create(LibraryItem)
LibraryItemFacade -> DAOFactory : getLibraryItemDAO()
DAOFactory -> LibraryItemDAO++ : <<create>>
LibraryItemDAO -> DAOFactory
DAOFactory -> LibraryItemFacade : libraryItemDAO
LibraryItemFacade -> LibraryItemDAO : create(LibrayItem)
LibraryItemDAO -> LibraryItemFacade : libraryItem
deactivate LibraryItemDAO
LibraryItemFacade -> LibraryItemFormController : libraryItem

@enduml