@startuml

package controller {
  class RecommandationController {
    -type: Select
    -category: TextField
    -cdd: TextField
    -name: TextField
    -other: TextField
    -search: Button
    -recommandations: Item[]
    +filter(): void
    +computeRecommandations(): void
  }
}

package Auth {
  class Session {
    +getLoggedInClient()
  }
}

package recommandation {
  class RecommandationFacade {
    +computeRecommandations()
  }
  class RecommandationSystem {
    +compute(Client, Rating[])
  }
}

package dao {
  abstract class DAOFactory {
    +getRatingDAO(): RatingDAO
  }

  interface RatingDAO {
    +getAllRatings(): Rating[]
  }
  
  interface LibraryItemDAO {
    +getLibraryItemBtId(String): LibraryItem
  }

  package postgres {

    class PostgresRatingDAO implements RatingDAO {
      -connection: Connection
      +PostgresRatingDAO(Connection: connection)
    }
    
    class PostgresLibraryItemDAO implements LibraryItemDAO {
      -connection: Connection
      +PostgresLibraryItemDAO(Connection: connection)
    }

    class PostgresDAOFactory extends DAOFactory {
      -connection: Connection
    }

  }

}
RecommandationFacade -> Session
PostgresDAOFactory .left> PostgresRatingDAO : "creates"
PostgresDAOFactory .right> PostgresLibraryItemDAO : "creates"
DAOFactory .left> RatingDAO : "provides"
DAOFactory .right> LibraryItemDAO : "provides"

' Inter-packages relations

RecommandationFacade -down-> DAOFactory
RecommandationFacade -left> RecommandationSystem
RecommandationController --> RecommandationFacade

@enduml
