@startuml
autonumber

- -> ItemSearchController: search()
ItemSearchController -> ItemSearchFacade: search(String,String,String,String,String)
ItemSearchFacade -> DAOFactory : getLibraryItemDAO()
DAOFactory -> LibraryIteamDAO ++ : <<creates>>
LibraryIteamDAO -> DAOFactory
DAOFactory -> ItemSearchFacade : LibraryIteamDAO
ItemSearchFacade -> LibraryIteamDAO : findByFilter(String,String,String,String,String)
LibraryIteamDAO -> ItemSearchFacade : LibraryItem[]
deactivate LibraryIteamDAO
alt search was succeed
  ItemSearchFacade -> ItemSearchController : LibraryItem[] was returned
else no result
  ItemSearchFacade -> ItemSearchController: No result
else search cancelled
  ItemSearchFacade -> ItemSearchController: search cancelled error
else new search
  - -> ItemSearchController: newSearch()
else any other error
  ItemSearchFacade -> ItemSearchController: internal error
end
@enduml
