@startuml
package controller {

  class ItemSearchController {
    -typeField: TextField
    -cardIdOrNameField: TextField
    -categoryField: TextField
    -cddField: TextField
    -authorsField: TextField
    -searchButton: Button
    +search() : void
  }
}

package item-search {

  class ItemSearchFacade {
    +search(String type, String category, String cdd, String cardId, String authors) : LibraryItem[]
  }
  note top of ItemSearchFacade
   Attributes can be Null
  end note

}

package dao {

  abstract class DAOFactory {
    +getLibraryItemDAO(): LibraryItemDAO
  }

  interface LibraryItemDAO {
    +findByFilter(String type, String category, String cdd, String cardId, String authors) : LibraryItem[]
  }

  package postgres {

    class PostgresLibraryItemDAO implements LibraryItemDAO {
      -connection: Connection
      +PostgresLibraryItemDAO(Connection: connection)
    }

    class PostgresDAOFactory extends DAOFactory {
      -connection: Connection
    }
  }

}

PostgresDAOFactory .left> PostgresLibraryItemDAO : "creates"
DAOFactory .left> LibraryItemDAO : "provides"
ItemSearchFacade -down-> DAOFactory
ItemSearchController -down-> ItemSearchFacade
@enduml