@startuml Authentication use cases

left to right direction

actor User as U
actor Employee as E
actor Client as C
actor Administrator as A

rectangle "Authentication" {
  usecase "Connect as employee" as CaE
  note right: Using username and password
  
  usecase "Connect as client" as CaC
  note right: Using client ID
  
  usecase "Connect as administrator" as CaA
  note right: Using username and password
  
  usecase "Disconnect" as D
}

U -- CaE
U -- CaC
U -- CaA
A -- D
E -- D
C -- D

@enduml