@startuml

autonumber

-> FineController : delete()
FineController -> FinesFacade : delete(fineId)
FinesFacade -> DAOFactory : getFineDAO()
DAOFactory -> FineDAO++
FineDAO -> DAOFactory
DAOFactory -> FinesFacade : fineDao
FinesFacade -> FineDAO : delete(fineId)

@enduml