@startuml Manage returns

left to right direction

actor Employee as E

rectangle "Manage returns" {
  usecase "Return document" as R
  usecase "Create fine" as F
}

E -- R
R <-. F : extends

@enduml
