@startuml Search items

left to right direction

actor Employee as E

rectangle "Find items" {
  usecase "Search items" as S
  usecase "Find location" as F
}

E -- S
F .> S : "extends"

note right of F
  If the item exists
end note


@enduml
